config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :index]
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :yandex_translates
  root 'welcome#index'

end

app/models/translate.rb
class Translate < ActiveRecord::Base
  private
    Key = "trnsl.1.1.20150807T193721Z.a28754c35f356a3c.9887c0360b34c7c397a5f114144c28840912b234"

  yandex = YandexTranslate::Client.new(Key)

  belongs_to :user

  validates :text, presence: true
  validates :translated_text, presence: true
  validates :lang, presence: true

  before_validation do
    self.lang = "en-ru"
    self.lang = "ru-en" if yandex.detect(text) == 'ru'
    self.translated_text = yandex.translate(text, lang)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Translate

  # before_validation do
  #   self.role = 1
  #   self.role = 0 if User.count == 0
  # end

  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.deliver_password_reset_instructions!
      flash[:success] = "Instructions to reset your password have been emailed to you."
      redirect_to root_path
    else
      flash[:warning] = "No user was found with that email address"
      render :new
    end
  end

  def edit
    @user = User.find_by(perishable_token: params[:id])
  end

  def update
    @user = User.find_by(perishable_token: params[:id])
    if @user.update_attributes(password_reset_params)
      flash[:success] = "Password successfully updated!"
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def password_reset_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:success] = "Welcome back!"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = "Goodbye!"
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Account registered!"
      redirect_to root_path
    else
      render :new
    end
  end

  def index
  end

  private
    def users_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def create
  begin
    @subscription = Actors::Customer::UseCases.subscribe_to_a_plan(current_user.email,
                                                                   params[:stripeToken],
                                                                   params[:plan_name],
                                                                   logger)
  rescue Striped::CreditCardDeclined => e
    redisplay_form(e.message)
  rescue Striped::CreditCardException, Exception => e
    redisplay_form("Subscription failed. We have been notified about this problem.")
  end

end
end

app/controllers/yandex_translates_controller.rb
class YandexTranslatesController < ApplicationController

  def index
      @translates = Translate.all.where(user_id: current_user.id)
  end

  def show
      @translate = Translate.find_by(id: params[:id], user_id: current_user.id)
  end

  def new
    @translate = Translate.new
  end

  def edit
      @translate = Translate.find_by(id: params[:id], user_id: current_user.id)
  end

  def create
    @translate = Translate.new(text: translate_params[:text], user_id: current_user.id)

    if @translate.save
      redirect_to :action => 'show', :id => @translate
    else
      render 'new'
    end
  end

  def update
    @translate = Translate.find(params[:id])

    if @translate.user_id == current_user.id && @translate.update(text: translate_params[:text])
      redirect_to :action => 'show', :id => @translate
    else
      render 'edit'
    end
  end

  def destroy
    @translate = Translate.find(params[:id])
    @translate.destroy if @translate.user_id == current_user.id
    redirect_to yandex_translates_path
  end

  private
    def translate_params
      params.require(:translate).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/yandex_translates_helper.rb
module YandexTranslatesHelper

end

app/views/layouts/application.html.slim
doctype html
html
head
  title Yandex Translate
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

body

  nav class="navbar navbar-inverse"
    div class="container"

      div class="navbar-header"
        = link_to 'Plyumbus', root_path, class: 'navbar-brand'

      div id="navbar"

        ul class="nav navbar-nav"
          li = link_to 'Home', root_path
          - if current_user
            li = link_to "All Translate", yandex_translates_path
            li = link_to 'New translate', new_yandex_translate_path

        ul class="nav navbar-nav pull-right"
          - if current_user
              li
                span
                  = link_to current_user.email, users_path
              li = link_to 'Sign Out', sign_out_path, method: :delete
          - else
              li = link_to 'Sign In', sign_in_path
              li = link_to 'Sign Up', new_user_path

  = yield

app/views/password_resets/edit.html.slim
div class="container"
  div class="col-md-3"
    div class="page-header"
      h1 Reset password

    = form_for @user, url: password_reset_path, method: :patch do |f|
      = render 'shared/errors', object: @user

      div class="form-group"
        = f.label :password
        = f.password_field :password, class: 'form-control'

      div class="form-group"
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control'

      = f.submit "Reset!", class: 'btn btn-primary'

app/views/password_resets/new.html.slim
div class="container"
  div class="col-md-3"
    div class="page-header"
      h1 Forgot your password?

    = form_tag password_resets_path, method: :create do
      div class="form-group"
        = label_tag 'email', 'E-mail'
        = email_field_tag 'email', nil, class: 'form-control'

      = submit_tag 'Send reset instructions', class: 'btn btn-primary'

app/views/shared/_errors.html.slim
- if object.errors.any?
  div class="panel panel-warning errors"
    div class="panel-heading"
      h5
        i class="glyphicon glyphicon-exclamation-sign" Found errors while saving

    ul class="panel-body"
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/user_sessions/new.html.slim
div class="container"
  div class="col-md-3"
    div class="page-header"
      h1 Sign In

    = form_for @user_session do |f|
      = render 'shared/errors', object: @user_session

      div class="form-group"
        = f.label :email
        = f.email_field :email, class: 'form-control'

      div class="form-group"
        = f.label :password
        = f.password_field :password, class: 'form-control'

      div class="form-group"
        = f.label :remember_me
        = f.check_box :remember_me

      = f.submit "Log in!", class: 'btn btn-primary btn-lg'
      br
      br
      = link_to 'Forgot your password?', new_password_reset_path, class: 'btn btn-sm btn-default'

app/views/users/index.html.slim
- if current_user
  div class="container"
    div class="page-header"
      h1 Welcome back!

    h2 Some info about you...

    div class="well well-lg"
      ul
        li Login count:
        = current_user.login_count
        li Failed login count:
        = current_user.failed_login_count
        li Last request:
        = current_user.last_request_at
        li Current login at:
        = current_user.current_login_at
        li Last login at:
        = current_user.last_login_at
        li Current login IP:
        = current_user.current_login_ip
        li Last login IP:
        = current_user.last_login_ip
- else
  div class="page-header"
    h1 Please Sing In!

app/views/users/new.html.slim
div class="container"
  div class="col-md-3"
    div class="page-header"
      h1 Register

    = form_for @user do |f|
      = render 'shared/errors', object: @user

      div class="form-group"
        = f.label :email
        = f.email_field :email, class: 'form-control'
      div

      div class="form-group"
        = f.label :password
        = f.password_field :password, class: 'form-control'

      div class="form-group"
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control'

      = f.submit 'Register', class: 'btn btn-primary btn-lg'

app/views/welcome/index.html.slim
div class="jumbotron"
  div class="container text-center"
    h1 Welcome to Yandex Translate
    - if current_user
      p
        br
        = link_to "All Translate", yandex_translates_path, class: 'btn btn-primary btn-lg', style: "margin-right: 20px;"
        = link_to 'New translate', new_yandex_translate_path, class: 'btn btn-primary btn-lg'
    - else

      p Sign Up to get started or Sing In.
      p
        = link_to "Sign Up", new_user_path, class: 'btn btn-primary btn-lg',  style: "margin-right: 20px;"
        = link_to 'Sign In', sign_in_path, class: 'btn btn-primary btn-lg'

app/views/yandex_translates/_form.html.slim
= form_for :translate, url: url, method: method do |f|
  p class="text-center"
    = f.label :text, 'Translated text'
    - if @translate.errors[:text].any?
      div class="error_explanation text-center"
        ul
          - @translate.errors[:text].each do |msg|
            li = msg
        = f.text_area :text
    - else
      br
      = f.text_area :text, :value => @translate.text
      br
      br
    = f.submit :Translate, class: 'btn btn-success btn-lg'

app/views/yandex_translates/edit.html.slim
div class="container text-center"
  div class="page-header"
    h1 All Translate
  = render partial: "yandex_translates/form", locals: {translate: @translate, url: yandex_translate_path(@translate), method: :patch}
  = link_to 'Back', yandex_translates_path, class: 'btn btn-primary btn-lg'

app/views/yandex_translates/index.html.slim
div class="container"
  div class="page-header"
    h1 All Translate

  = link_to 'New translate', new_yandex_translate_path, class: 'btn btn-primary btn-lg'
  br
  br

  table class="table table-striped text-center"
    tr
      / - if current_user.role == "admin"
      /   th Email
      th class="text-center"  Text
      th class="text-center"  Translation direction
      th class="text-center"  Translated text
      th class="text-center"  Show
      th class="text-center"  Edit
      th class="text-center"  Destroy


    - @translates.each do |translate|
      tr
        / - if current_user.role == "admin"
        /   td = User.find(translate.user_id).email
        td = translate.text
        td = translate.lang
        td = translate.translated_text
        td = link_to 'Show', yandex_translate_path(translate)
        td = link_to 'Edit', edit_yandex_translate_path(translate)
        td = link_to 'Destroy', yandex_translate_path(translate), method: :delete, data: { confirm: 'Are you sure?' }
    end

app/views/yandex_translates/new.html.slim
div class="container text-center"
  div class="page-header"
    h1 Yandex Translate
  = render partial: "yandex_translates/form", locals: {translate: @translate, url: yandex_translates_path, method: ""}
  = link_to 'Back', yandex_translates_path, class: 'btn btn-primary btn-lg'

app/views/yandex_translates/show.html.slim
div class="container text-center"
  div class="page-header"
    h1 All Translate
  p
    strong Text:
    br
    = @translate.text

  p
    strong Translation direction:
    br
    = @translate.lang

  p
    strong Translated text:
    br
    = @translate.translated_text

  = link_to 'Back', yandex_translates_path